enum ActionType {
	INIT = "INIT",
	TITLE = "TITLE",
	TAG_FILTER = "TAG_FILTER",
	ADD_ITEM = "ADD_ITEM",
	SELECTED_ITEM = "SELECTED_ITEM",
	SELECTED_ITEM_NEXT = "SELECTED_ITEM_NEXT",
	SELECTED_ITEM_PREV = "SELECTED_ITEM_PREV",
	SELECTED_TAG = "SELECTED_TAG",

}
export default ActionType;
