enum ActionType {
	INIT = "INIT",
	TITLE = "TITLE",
	TAG_FILTER = "TAG_FILTER",
	ADD_ITEM = "ADD_ITEM",
	SELECTED_ITEM = "SELECTED_ITEM",
	SELECTED_ITEM_NEXT = "SELECTED_ITEM_NEXT",
	SELECTED_ITEM_NEXT_ACTIVE_VIEW = "SELECTED_ITEM_NEXT_ACTIVE_VIEW",
	SELECTED_ITEM_PREV = "SELECTED_ITEM_PREV",
	SELECTED_ITEM_PREV_ACTIVE_VIEW = "SELECTED_ITEM_PREV_ACTIVE_VIEW",
	SELECTED_TAG = "SELECTED_TAG",
	SELECTED_BOOK = "SELECTED_BOOK",
	MOVE_UP = "MOVE_UP",
	MOVE_DOWN = "MOVE_DOWN",
	MOVE_LEFT = "MOVE_LEFT",
	MOVE_RIGHT = "MOVE_RIGHT",
}
export default ActionType;
